=== Meromorph-Sound/Reason-NoiseSynth/XML/patch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="JukeboxPatch">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DeviceNameInEnglish" type="xs:string"/>
                <xs:element name="Properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Object">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Value" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="property" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="type" type="xs:string"
                                                  use="required"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="deviceProductID" type="xs:string" use="required"/>
                        <xs:attribute name="deviceVersion" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:float" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Meromorph-Sound/Reason-NoiseSynth/XML/Sinus.xml
<?xml version="1.0"?>
<JukeboxPatch version="1.0"  xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file://patch.xsd">
    <DeviceNameInEnglish>
        Simple Instrument
    </DeviceNameInEnglish>
    <Properties deviceProductID="se.propellerheads.SimpleInstrument"  deviceVersion="1.0.0d1" >
        <Object name="custom_properties" >
            <Value property="volume"  type="number" >
                0.7
            </Value>
            <Value property="frequency"  type="number" >
                0
            </Value>
            <Value property="sampleplay"  type="boolean" >
                false
            </Value>
            <Value property="waveform"  type="number" >
                0
            </Value>
        </Object>
    </Properties>
</JukeboxPatch>
